# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=None)),
                ('province', models.CharField(max_length=20)),
                ('crop', models.CharField(max_length=20)),
                ('type_db', models.CharField(max_length=20)),
                ('account', models.FloatField(default=None)),
            ],
        ),
    ]
